feat: Initial setup for api server, queue server, mongoose
relaycorp/awala-endpoint-internet pull request #18
Opened 2023-05-03 06:34 UTC by levansuper

closes: #7

2023-05-03 10:01 UTC, gnarea commented on src/client/QueueProblemType.ts
> +export enum QueueProblemType {
Similar thing as with the use of "API". When porting things from the Authority server, please make sure you use the correct terminology here.

2023-05-03 10:04 UTC, gnarea commented on src/client/server.ts
> +};
As discussed yesterday on the call, we should keep this simple and not borrow the sink mapping mini-framework we used in the Authority server.

The only event type this server will ever process are outgoing messages.

2023-05-03 10:06 UTC, gnarea commented on src/client/server.spec.ts
> +      });
Again, please pay attention to the things you port from the Authority server. Nothing related to `AWALA_MIDDLEWARE_ENDPOINT` makes sense in this app.

2023-05-03 10:07 UTC, gnarea commented on src/client/sinks/sinkTypes.ts
> +  readonly awalaMiddlewareEndpoint: URL;
Why is this here?

2023-05-03 10:08 UTC, gnarea commented on src/testUtils/envVars.ts
> +  AUTHORITY_VERSION: '1.2.3',
Again, please be careful with the things you port from the authority server.

2023-05-03 10:19 UTC, gnarea commented on src/utilities/logging.spec.ts
> +  test('App name should be "veraid-authority" if LOG_ENV_NAME if absent', () => {
Another reference to the Authority server.

2023-05-03 10:26 UTC, gnarea commented
> Please go over all the references to "API server" and "(background) queue" and replace them with the correct terminology here.

To clarify, here we don't have an API server or a background queue. We have a PoHTTP server and client.

2023-05-03 23:14 UTC, gnarea requested changes
Nearly there

2023-05-03 23:14 UTC, gnarea commented on src/example.ts
Why are we including this here?

2023-05-03 23:14 UTC, gnarea commented on src/utilities/logging.ts
> -  const gatewayVersion = env.get('AUTHORITY_VERSION').required().asString();
This shouldn't have been deleted. Whilst optional, the version is very important when troubleshooting -- we use it in GCP Error Reporting.

The only problem was the "AUTHORITY" bit. It should be something like `ENDPOINT_VERSION` here. We could event shorten it to "VERSION".

Make sure to restore this env var in `src/testUtils/envVars.ts`.

2023-05-04 07:32 UTC, levansuper commented on src/example.ts
Several tools are used in this file; if we delete the file, we will have to delete them too because they are not used anywhere else and we will get lint errors. ServiceOptions, mockEmitter, getPromiseRejection. We will need to create some business logic files anyways so I'll just rename this one.

2023-05-04 09:06 UTC, gnarea commented on src/example.ts
I see. That's outside the scope of #7, which is literally just about implementing the healthchecks. But I'll ignore that so we can merge this PR soon.

2023-05-04 09:08 UTC, gnarea approved these changes

2023-05-04 09:20 UTC, merged